### ISSUE TITLE
Two icons in the dock

### ISSUE THREAD

**Issue by thomn** [alexlarsson/spotify-app#1]
When Spotify starts, a second, low resolution icon appears in the dock, which is linked to the application window.
![Screenshot](https://cloud.githubusercontent.com/assets/4236851/14757003/99319bbe-08ef-11e6-98ab-3c34bc69e6d7.png)

**Comment by alexlarsson** [comment]
Ok, so one is the favourite launcher, and the other is the running instance.
I wonder why gnome-shell fails to know they are the same though.

**Comment by alexlarsson** [comment]
fixed in master
