### ISSUE TITLE
Runtime switch to Gnome for cursor integration

### ISSUE THREAD

**Issue by ghost** [alexlarsson/spotify-app#12]
I've noticed that cursor changes from Gnome's to that of default X11 icon when entering the app area. This is just a minor pet peeve, and I've found that relying on Gnome 3.20 runtime makes it integrate better and not do that - I imagine this will be different for KDE folks. Any thoughts on this?

**Comment by alexlarsson** [comment]
I updated spotify to use the gnome platform which will help with this.
Also, we've started packaging icon themes as flatpaks will will also help.
