### ISSUE TITLE
Can't use "Log in with Facebook" and other "web-related" features

### ISSUE THREAD

**Issue by petersaints** [alexlarsson/spotify-app#14]
First of all, thanks for your hard work. 
I've tried to use this Flatpack on Fedora 25 and everything went fine. I was able to build the "com.spotify.Client" package, install it and launch it with no issues. Unfortunately I'm unable to log in into my account.

I have a Facebook bound account and this type of account needs to start the login process though your web browser. However, Spotify just doesn't do anything when I click on the "Log in with Facebook" button. I believe that this is because the Flatpack is unaware of the environment's default browser and just doesn't now what to do. Still, I'm sure that there must be a way to change the build to process in order to be able to just launch the default browser to log in into Spotify through Facebook.

Besides the main issue, which is the ability to log in into my account and start to listen to music. Other buttons and links that need to link/launch a web page are also unable to work due to the same problem.

I hope that someone has any idea on how to fix this so that the Flatpack gets better, more complete, and, more importantly, it is able to be used by users who have a Facebook bound account such as myself.

**Comment by alexlarsson** [comment]
Hmm, i have a traditional spotify account, so I haven't tested this. However, we should be able to use the portals for showing the browser, although it may require changes to spotify to do that, so i'm not sure how easy that will be.

**Comment by rmartensen** [comment]
Same problem, I can't use this flatpak because I can't login with FB and the application crashes when I sign-in with traditional login.

**Comment by alexlarsson** [comment]
I pushed a new version that uses the desktop portal to open the browser.  Update, make sure xdg-desktop-portal-gtk is installed (its in F25), and then try again.

I don't have a facebook spotify command, so I can't test this.

**Comment by bjornwsv** [comment]
Same problem on Arch.

Installed xdg-desktop-portal-gtk from [AUR](https://aur.archlinux.org/packages/xdg-desktop-portal-gtk/), and updated.

    $ flatpak run com.spotify.Client
    /app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)

    (process:3): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
    Gtk-Message: Failed to load module "canberra-gtk-module"
    /app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
    [0118/103226:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
    /proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
    [0118/103226:ERROR:proxy_config_service_linux.cc(272)] Error requesting gconf directory: Failed to activate configuration server: org.freedesktop.DBus.Error.ServiceUnknown

    [0118/103226:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak

**Comment by alexlarsson** [comment]
@bjornwsv What exactly happens after that, because for me it prints that too, and then it works.

**Comment by bjornwsv** [comment]
It opens, but clicking on "login with Facebook" does nothing. Nothing prints in the terminal either.

**Comment by alexlarsson** [comment]
Gah, i forgot to push the new build. Can you update and try again

**Comment by bjornwsv** [comment]
Thank you. Everything works:)

**Comment by alexlarsson** [comment]
Cool
