### ISSUE TITLE
How to update installation with new version?

### ISSUE THREAD

**Issue by fusion809** [alexlarsson/spotify-app#17]
Hi,

I Googled this, in the hope that the answer would be in the documentation of Flatpak, but sadly I found no useful results. I just updated my local build of Spotify Flatpak to 1.0.44.100, how do I update my local Flatpak installation of Spotify accordingly? 

Thanks for your time,
Brenton

**Comment by alexlarsson** [comment]
If you added a remore for the local repo and installed it from there you should be able to do:
`flatpak update com.spotify.Client`. Or even just `flatpak update` to update everything. You might also need a `--user` in there if you installed as user.
