### ISSUE TITLE
You replaced xdg-app with Flatpak in README but not in the repo description

### ISSUE THREAD

**Issue by fusion809** [alexlarsson/spotify-app#19]
Hi,

Fairly minor issue but when you edited the README.md replacing xdg-app with Flatpak you probably should also have edited the description of this repo on GitHub. That is, the thing boxed in red in this screenshot:

![screenshot_20161220_120538](https://cloud.githubusercontent.com/assets/4717341/21335788/f31eb8f2-c6ac-11e6-94e1-c02129882bf5.png)

Thanks for your time,
Brenton

**Comment by alexlarsson** [comment]
Fixed, thanks.
