### ISSUE TITLE
.deb file not found

### ISSUE THREAD

**Issue by rmartensen** [alexlarsson/spotify-app#20]
Can't install because the .deb file is outdated / not found on the Spotify servers.
See output below

Installing: com.spotify.Client/x86_64/master
Updating: org.freedesktop.Platform/x86_64/1.4 from gnome
No updates.
Updating: org.freedesktop.Platform.Locale/x86_64/1.4 from gnome
No updates.
Installing: com.spotify.Client/x86_64/master from com.spotify.Client-1-origin

Downloading extra data 0 bytes/72,2 MB                                                           
error: While downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.45.182.gbbd5909f-72_amd64.deb: Server returned status 404: Not Found

**Comment by alexlarsson** [comment]
Should work now, thanks for the notice.
