### ISSUE TITLE
Please add required dependencies in readme

### ISSUE THREAD

**Issue by indivisualist** [alexlarsson/spotify-app#22]
Since I stumbled upon the GitHub repo first, the required dependency should be mentioned in the readme file:
`flatpak remote-add gnome https://sdk.gnome.org/gnome.flatpakrepo`
This would be helpful for others who aren't familiar with Flatpak.

**Comment by rmartensen** [comment]
I agree but `flatpak remote-add --if-not-exists gnome https://sdk.gnome.org/gnome.flatpakrepo` would be better.
