### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by da2x** [alexlarsson/spotify-app#24]
flatpak install --from https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref --user
Installing: com.spotify.Client/x86_64/master
Updating: org.freedesktop.Platform/x86_64/1.4 from gnome
No updates.
Updating: org.freedesktop.Platform.Locale/x86_64/1.4 from gnome
No updates.
Installing: com.spotify.Client/x86_64/master from com.spotify.Client-2-origin

Downloading extra data 0 bytes/72,2 MB                                                                                                                                                                             
error: While downloading http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.45.186.g3b5036d6-95_amd64.deb: Server returned status 404: Not Found

**Comment by alexlarsson** [comment]
I guess there was a new spotify release we need to update to

**Comment by alexlarsson** [comment]
Should work now, i updated to the latest version.
