### ISSUE TITLE
error: While downloading http://repository-origin.spotify.com ...  1.0.47.13

### ISSUE THREAD

**Issue by jgarciao** [alexlarsson/spotify-app#29]
I just tried to install spotify from http://flatpak.org/apps.html and it failed with this error

                                                                                                                                               
`error: While downloading http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.47.13.gd8e05b1f-89_amd64.deb: Server returned status 404: Not Found`

It looks like they released today a new version and removed the 1.0.47
http://repository-origin.spotify.com/pool/non-free/s/spotify-client/

Thank you for your work!

**Comment by alexlarsson** [comment]
Should work now.

**Comment by jgarciao** [comment]
Thanks!
