### ISSUE TITLE
Pass argments to spotify

### ISSUE THREAD

**Issue by benwaffle** [alexlarsson/spotify-app#31]
For example, I need `--force-device-scale-factor=2` for HiDPI

**Comment by alexlarsson** [comment]
You can do this as `flatpak run com.spotify.Client --force-device-scale-factor=2`

**Comment by benwaffle** [comment]
That does not work for me

**Comment by alexlarsson** [comment]
Ah, i need to forward args in the shell wrapper
lemme fix

**Comment by alexlarsson** [comment]
Should work now, just flatpak update and go

**Comment by benwaffle** [comment]
just curious, why is there no commit for this?

**Comment by alexlarsson** [comment]
ah, forgot to push it to github
