### ISSUE TITLE
Spotify doesn't work: Gtk-WARNING **: cannot open display: :99.0

### ISSUE THREAD

**Issue by nicber** [alexlarsson/spotify-app#33]
I'm running OpenSUSE Tumbleweed with the latest updates and Flatpak version 0.8.3.
I get this error when trying to run Spotify.

```
nicolas@linux-m62g:~> flatpak run com.spotify.Client 
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
No protocol specified

(spotify:2): Gtk-WARNING **: cannot open display: :99.0

```
It is relevant that it used to work in the past.

**Comment by alexlarsson** [comment]
This means you have issues with x authtentication. There is a fix for this in 0.8.4, or you can use xhost + to work around if for now.
