### ISSUE TITLE
Running 'make' fails due to read-only file system

### ISSUE THREAD

**Issue by jadahl** [alexlarsson/spotify-app#34]
Running make fails with

> Cannot open /usr/share/gtk-doc/html: No such file or directory
> stripping /home/jonas/Dev/flatpaks/spotify-app/.flatpak-builder/rofiles/rofiles-FHJFYY/files/libexec/udevd to /home/jonas/Dev/flatpaks/spotify-app/.flatpak-builder/rofiles/rofiles-FHJFYY/files/lib/debug/libexec/udevd.debug
> eu-strip: while opening '/home/jonas/Dev/flatpaks/spotify-app/.flatpak-builder/rofiles/rofiles-FHJFYY/files/libexec/udevd': Read-only file system
> Error: module udev: Child process exited with code 1
> Makefile:6: recipe for target 'test' failed
> make: *** [test] Error 1

I'm doing this on F25.

**Comment by alexlarsson** [comment]
Thats weird. It built here. What flatpak-builder version do you have installed?

**Comment by jadahl** [comment]
i have 0.9.1.

**Comment by alexlarsson** [comment]
Are you *sure*, because this sounds exactly like what was fixed by: https://github.com/flatpak/flatpak/commit/5a3c7feb1539d2d924f0ff9e1294530ea1585fc1

**Comment by jadahl** [comment]
After running git clean -fdx.

```
$ flatpak-builder --version
Flatpak 0.9.1
$ make
ostree init --mode=archive-z2 --repo=repo
flatpak-builder --force-clean --repo=repo --ccache --require-changes spotify com.spotify.Client.json
```
.. configuring, building, etc, ending with:
```
Making install in libudev/docs
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/install -c -m 644 ./html/api-index-full.html
 /usr/bin/install -c -m 644 ./html/ch01.html
 /usr/bin/install -c -m 644 ./html/home.png
 /usr/bin/install -c -m 644 ./html/index.html
 /usr/bin/install -c -m 644 ./html/index.sgml
 /usr/bin/install -c -m 644 ./html/left.png
 /usr/bin/install -c -m 644 ./html/libudev-udev-device.html
 /usr/bin/install -c -m 644 ./html/libudev-udev-enumerate.html
 /usr/bin/install -c -m 644 ./html/libudev-udev-list.html
 /usr/bin/install -c -m 644 ./html/libudev-udev-monitor.html
 /usr/bin/install -c -m 644 ./html/libudev-udev-queue.html
 /usr/bin/install -c -m 644 ./html/libudev-udev-util.html
 /usr/bin/install -c -m 644 ./html/libudev-udev.html
 /usr/bin/install -c -m 644 ./html/libudev.devhelp2
 /usr/bin/install -c -m 644 ./html/right.png
 /usr/bin/install -c -m 644 ./html/style.css
 /usr/bin/install -c -m 644 ./html/up.png
Cannot open /usr/share/gtk-doc/html: No such file or directory
stripping /home/jonas/Dev/flatpaks/spotify-app/.flatpak-builder/rofiles/rofiles-V0D7XY/files/libexec/udevd to /home/jonas/Dev/flatpaks/spotify-app/.flatpak-builder/rofiles/rofiles-V0D7XY/files/lib/debug/libexec/udevd.debug
eu-strip: while opening '/home/jonas/Dev/flatpaks/spotify-app/.flatpak-builder/rofiles/rofiles-V0D7XY/files/libexec/udevd': Read-only file system
Error: module udev: Child process exited with code 1
Makefile:6: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by jadahl** [comment]
I found the issue. I was running this within a jhbuild session, but with a custom "unjhbuild" command to get an un-jhbuild:ed environment. That command didn't do enough. What it did was reset LD_LIBRARY_PATH, GI_TYPELIB_PATH and PYTHONPATH. Also resetting PATH made things build.

**Comment by pacuna** [comment]
@jadahl I'm having the same issue in F26. Can you explain a little bit how did you solve it?
Thanks.

**Comment by jadahl** [comment]
@pacuna I ran into the issue when I was running make from within jhbuild <https://www.freedesktop.org/wiki/Software/jhbuild/>.

jhbuild is a system that enables you to have a separate set of software packages (not .deb or .rpm packages!) automatically built and installed into a dedicated directory. It's often used when developing the GNOME platform and GNOME applications.  What it does, simply speaking, is it sets various environmental variables such as PATH, LD_LIBRARY_PATH and many others to make things try searching for programs and libraries in the dedicated directory before trying the one installed by your distribution.

What I did to fix the issue was to make sure I was no longer trying to build the flatpak from within jhbuild.

Are you trying this from the default F26 session? What version of flatpak-builder do you have installed?

**Comment by pacuna** [comment]
@jadahl Yes I'm just following the instructions in [this link](https://fedoraproject.org/wiki/Spotify). My version is Flatpak 0.9.1. Any ideas ? I'm getting the same error when running make:

    Cannot open /usr/share/gtk-doc/html: No such file or directory
    stripping /home/pacuna/code/external/spotify-app/.flatpak-builder/rofiles/rofiles-6GUXYY/files/libexec              /udevd to /home/pacuna/code/external/spotify-app/.flatpak-builder/rofiles/rofiles-6GUXYY/files/lib/debug /libexec/udevd.debug
    Error: module udev: Failed to execute child process “eu-strip” (No such file or directory)
    make: *** [Makefile:6: test] Error 1

**Comment by jadahl** [comment]
@pacuna That is a different issue from what I had. I suggest first upgrading to flatpak-builder 0.9.2 (I think its in F26 already), and if the problem persists, open a new issue.

**Comment by pacuna** [comment]
@jadahl I updated flatpak and I'm still getting the issue so I'll probably going to open a new issue.
Thanks!

**Comment by alexlarsson** [comment]
YEah, thats seems to be a packaging error. flatpak-builder should depend on elfutils, so installing it should fix this for you.

**Comment by pacuna** [comment]
@alexlarsson thanks man! That did the trick.
