### ISSUE TITLE
MP3 local files won't play due to missing ffmpeg libraries

### ISSUE THREAD

**Issue by ace13** [alexlarsson/spotify-app#38]
A few Spotify issues regarding this problem;
[1353908](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Linux-Local-files-do-not-play-on-Ubuntu-16-04-SOLVED/m-p/1353908)
[1578426](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Can-t-play-local-files-with-current-version-of-ffmpeg/m-p/1578426#M178037)
[1353908](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Linux-Local-files-do-not-play-on-Ubuntu-16-04-SOLVED/m-p/1353908#M157355)

The problem seems to be that Spotify expects exact versions of parts from ffmpeg, failing to play any local MP3's otherwise - possibly other formats as well.

The generally accepted solution seems to be to either install the `libavcodec54` and `libavformat54` libraries, or to [download the compiled versions](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Can-t-play-local-files-with-current-version-of-ffmpeg/m-p/1578426#M178037) of those libraries and put them in your lib folder.

The versions it seems to expect are;
libavcodec.so.54.71.100 as `libavcodec.so.54`
libavformat.so.54.36.100 as `libavformat.so.54`
Probably also libavutil.so.52.6.100 as `libavutil.so.52`

(On my local non-flatpak install, I'm currently using the linked libraries to solve the problem)

**Comment by alexlarsson** [comment]
Hmm, i really would prefer to build my own copy of ffmpeg than use some random binaries. But i can't seem to find the sources that match these versions. Do you have any idea?

**Comment by ace13** [comment]
Seems like it could be something from ffmpeg 1.1.x, possibly 1.2.x

**Comment by Lonsfor** [comment]
If the libraries wont be added to the repository any time soon, is there a way to manually add them?

**Comment by alexlarsson** [comment]
I haven't had time to look at this, but I would take a PR if anyone else wants to look at it.
