### ISSUE TITLE
HiDPI Support?

### ISSUE THREAD

**Issue by knaeckeKami** [alexlarsson/spotify-app#39]
Is it possible to add HiDPI support? Afaik it should only require to add something like --force-device-scale-factor=1.5 as a command line option, but this had no effect on my system.

**Comment by alexlarsson** [comment]
Did you try recently? This should have been fixed in https://github.com/alexlarsson/spotify-app/issues/31

**Comment by knaeckeKami** [comment]
flatpak run com.spotify.Client --force-device-scale-factor=2 does not start Spotify in HiDPI-mode. I didn't check if it is a bug in spotify or if flatpak does not pass the arguments correctly yet, though.

**Comment by alexlarsson** [comment]
That is very weird, i just tested it here on a hidpi laptop and it seems to work fine.

**Comment by knaeckeKami** [comment]
It could be a bug in the Spotify app. I am on Fedora 25 with Wayland. This is the output I get when I start it from command line:
` flatpak run com.spotify.Client --force-device-scale-factor=2
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
[0504/002121:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0504/002121:ERROR:proxy_config_service_linux.cc(272)] Error requesting gconf directory: Der Konfigurationsserver konnte nicht aktiviert werden: org.freedesktop.DBus.Error.ServiceUnknown

[0504/002121:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
[0504/002121:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
[0504/002121:ERROR:browser_gpu_channel_host_factory.cc(131)] Failed to create channel.
`

**Comment by alexlarsson** [comment]
That error is about the GL driver, but i don't think that should affect the scaling. I mean, the app still starts, right?

**Comment by knaeckeKami** [comment]
Yeah, the app still starts, but the scaling-argument seems to be ignored, eveything is very small on a hidpi screen. I don't think that you can do much about that, I installed the app from http://negativo17.org/repos/fedora-spotify.repo and this also has this bug, so it seems to be an issue with the spotify app, Fedora and possibly my hardware.

**Comment by alexlarsson** [comment]
The scaling works for me, but yeah, doesn't seem flatpak related.

**Comment by alexlarsson** [comment]
The scaling works for me, but yeah, doesn't seem flatpak related.
