### ISSUE TITLE
Flatpakref pulling version that does not exist

### ISSUE THREAD

**Issue by evil666** [alexlarsson/spotify-app#40]
So I attempted to install flatpak of spotify for the first time today. It didn't go so well because its trying to pull a version that does not exist in the repository.

`error: While downloading http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.52.717.g2f08534a-47_amd64.deb: Server returned status 404: Not Found`

However the current versions available are:
spotify-client_1.0.53.758.gde3fc4b2-33_amd64.deb 
and
spotify-client_1.0.49.125.g72ee7853-111_amd64.deb

**Comment by alexlarsson** [comment]
Yeah. They only keep the latest version. Will update.

**Comment by evil666** [comment]
Thanks and thanks for the uber fast reply!

**Comment by alexlarsson** [comment]
should work now
