### ISSUE TITLE
filesystem_error and crash when starting Spotify

### ISSUE THREAD

**Issue by pmk1c** [alexlarsson/spotify-app#41]
I get the following error when I try to start Spotify via this flatpak:

```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::temp_directory_path: Not a directory: "/tmp/tmp.U8QEljZmvv"
```

I'm on Fedora 25.

**Comment by pmk1c** [comment]
The problem seems to be, that `$TMPDIR` is set to `/tmp/tmp.U8QEljZmvv` in the flatpak sandbox. This is derived from the host. Wouldn't it be correct to overwrite `$TMPDIR` with `/tmp` in all flatpak sandboxes? Since we don't need user specific `tmp` folders.

**Comment by alexlarsson** [comment]
Yeah, we should probably do that.
