### ISSUE TITLE
Make /etc/hosts available to app

### ISSUE THREAD

**Issue by jonas2515** [alexlarsson/spotify-app#42]
Is there a way include the hosts file into the sandbox to make local resolving and ad-blocking possible?

I hope this isn't the wrong place to ask, I'm new to flatpak and know nothing about its architecture...

**Comment by alexlarsson** [comment]
We typically put the host /etc/resolv.conf in the sandbox, but ignore /etc/hosts. Maybe we should import it too...

**Comment by alexlarsson** [comment]
However, right now /etc/hosts is from the runtime and can't be changed.

**Comment by jonas2515** [comment]
Is there a way to import it by changing some flags or is this unsupported in flatpak?

**Comment by alexlarsson** [comment]
Not currently, no.
