### ISSUE TITLE
Spotify's .deb package filename has changed

### ISSUE THREAD

**Issue by michalrud** [alexlarsson/spotify-app#47]
When installing spotify the following error can be seen:

```
$ flatpak install --from https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref
Instalowanie: com.spotify.Client/x86_64/master
Instalowanie: com.spotify.Client/x86_64/master z com.spotify.Client-origin
[                    ] Downloading metadata: 0/(estimating) 0 bajtów (0 bajtów/s)
błąd: Podczas pobierania http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.55.487.g256699aa-16_amd64.deb: Server returned status 404: Not Found
```

Looking at Spotify's [deb repository](http://repository-origin.spotify.com/pool/non-free/s/spotify-client/), the filename is now `spotify-client_1.0.57.474.gca9c9538-30_amd64.deb`.

I cannot create a pull request right now to fix it, but if you don't have time to do it I will try to do it later this or next week - but these will be my first flatpak steps, so I don't know it I'll suceed 😄

**Comment by alexlarsson** [comment]
Thanks for the PR. updated the builds.
