### ISSUE TITLE
After update, spotify doesn't suddendly closes after started

### ISSUE THREAD

**Issue by marcosps** [alexlarsson/spotify-app#50]
Just updated my spotify using "flatpak update", and now it closes suddendly after run:

[marcos@Icarus ~]$ flatpak run com.spotify.Client
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)

(process:2): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: Failed to load module "pk-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0722/103508.312829:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

I'm using Fedora 26. If you need more info, please let me know.

**Comment by netscruff** [comment]
I'm having the same issue with Fedora 26. 
`
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
`

In the output of journalctl:
`Jul 25 00:03:19 maude.home systemd[2234]: Started flatpak-com.spotify.Client-28555.scope.
Jul 25 00:03:19 maude.home audit[28597]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=28597 comm="spotify" exe="/app/extra/share/spotify/spotify" sig=11 res=1
Jul 25 00:03:19 maude.home kernel: spotify[28597]: segfault at 33 ip 00007f0e1f922ce4 sp 00007fffbf710630 error 4 in libcef.so[7f0e1e1bc000+6e67000]
Jul 25 00:03:20 maude.home systemd[1]: Started Process Core Dump (PID 28603/UID 0).
Jul 25 00:03:20 maude.home audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@34-28603-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 25 00:03:20 maude.home audit[28564]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=4 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=28564 comm="spotify" exe="/app/extra/share/spotify/spotify" sig=11 res=1
Jul 25 00:03:20 maude.home kernel: spotify[28564]: segfault at 0 ip 00000000005f5d07 sp 00007fffc6c50fb8 error 6 in spotify[400000+23e8000]
Jul 25 00:03:20 maude.home systemd[1]: Started Process Core Dump (PID 28611/UID 0).
Jul 25 00:03:20 maude.home audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@35-28611-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 25 00:03:20 maude.home systemd-coredump[28604]: Process 28597 (spotify) of user 1000 dumped core.`
                                                    
                                                    Stack trace of thread 34:
                                                    #0  0x00007f0e1f922ce4 n/a (/app/extra/share/spotify/libcef.so)
`Jul 25 00:03:20 maude.home audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@34-28603-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 25 00:03:20 maude.home systemd-coredump[28612]: Process 28564 (spotify) of user 1000 dumped core.`
                                                    
                                                    Stack trace of thread 2:
                                                    #0  0x00000000005f5d07 n/a (/app/extra/share/spotify/spotify)
                                                    #1  0x00000000005f5d1d n/a (/app/extra/share/spotify/spotify)
                                                    #2  0x00000000015944df n/a (/app/extra/share/spotify/spotify)
                                                    #3  0x00007f74fd7e3415 n/a (/app/extra/share/spotify/libcef.so)

**Comment by alexlarsson** [comment]
Do you use the nvidia gpu driver?

**Comment by alexlarsson** [comment]
Or in general, what openGL driver are you using.

**Comment by netscruff** [comment]
Yes, I do use the nvidia driver.

**Comment by marcosps** [comment]
@alexlarsson it crashes n my desktop:
[marcos@Osiris ~]$ flatpak run org.freedesktop.GlxInfo  | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 4.0, 128 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.0.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

And in my laptop, which uses i965 from mesa.

**Comment by TomasTomecek** [comment]
I can confirm. It seems like the crash/segfault is caused by spotify itself. I even tried the older version (1.0.49) on different platforms: 3.22, 3.24 and the result is still the same.

```
$ flatpak run com.spotify.Client
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0802/132701.880355:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
```

**Comment by marcosps** [comment]
@alexlarsson there is something that we can do for helping you to fix this issue?

I don't know if the root cause is the same, but, another flatpak is also having problems with OpenGL and GPU stuff: https://github.com/gnome-mpv/gnome-mpv/issues/290

Please let me know if I can help you to debug this issue.

**Comment by TomasTomecek** [comment]
I created an upstream issue to track this: https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/official-linux-spotify-client-segfaults/td-p/1801635

**Comment by marcosps** [comment]
When using spotify from negativo repository on Fedora 26, it shows the same error about OpenGL, but the process goes on, without being shutdown:

[marcos@Icarus ~]$ 
[marcos@Icarus ~]$ spotify 
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /usr/lib64/spotify-client/libssl.so.1.0.0: no version information available (required by /usr/lib64/spotify-client/spotify)
/usr/lib64/spotify-client/spotify: /lib64/libcurl.so.4: no version information available (required by /usr/lib64/spotify-client/spotify)
/proc/self/exe: /usr/lib64/spotify-client/libcrypto.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /usr/lib64/spotify-client/libssl.so.1.0.0: no version information available (required by /proc/self/exe)
/proc/self/exe: /lib64/libcurl.so.4: no version information available (required by /proc/self/exe)
[0806/085839.776208:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain

SO this could be something related only to flatpak?

**Comment by christianbueno1** [comment]
hello , problem on fedora 26 kde plasma
the first command is ok
`flatpak install --from https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref`
the second command error , i remember had install it in the past
<pre><code>
[harvey@localhost ~]$ flatpak run com.spotify.Client
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0811/180133.923143:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
</pre></code>

**Comment by christianbueno1** [comment]
please , problems in fedora workstation(gnome 3.24)
i am following this [guide](http://flatpak.org/apps.html)
<pre><code>
 harvey  ~  flatpak run com.spotify.Client
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: Failed to load module "pk-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0811/194136.546891:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
</pre></code>

<pre><code>
 harvey  ~  uname -a
Linux localhost.localdomain 4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
</pre></code>

I had installed spotify by this way , today reintall fedora 26 and this is happening

**Comment by christianbueno1** [comment]
on the seventh try think , all was ok
<pre><code>
 harvey  ~  flatpak run com.spotify.Client
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)
Gtk-Message: Failed to load module "pk-gtk-module"
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)
[0811/200243.068134:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[0811/200243.295316:ERROR:interface_registry.cc(203)] Failed to locate a binder for interface: blink::mojom::SensitiveInputVisibilityService requested by: content_renderer exposed by: content_browser via InterfaceProviderSpec "navigation:frame".
[0811/200254.879611:ERROR:web_plugin_impl.cc(38)] Widevine registration is not supported after context initialization
[0811/200327.149768:ERROR:KeyboardEventManager.cpp(427)] Not implemented reached in static bool blink::KeyboardEventManager::currentCapsLockState()

</pre></code>
spotify is running on fedora 26 worstation(gnome)

**Comment by marcosps** [comment]
@alexlarsson  dmesg shows that libcef is crashing:

[12435.474460] spotify[24532]: segfault at 32 ip 00007f1bb81a5ce4 sp 00007fff8e10d300 error 4 in libcef.so[7f1bb6a3f000+6e67000]
[12435.975399] spotify[24384]: segfault at 0 ip 00000000005f5d07 sp 00007ffd6c6c4e38 error 6 in spotify[400000+23e8000]

I don't know if this helps...

**Comment by marcosps** [comment]
@alexlarsson I don't know, but today it just worked:

[marcos@Osiris config_files]$ flatpak run com.spotify.Client                                                           
/app/extra/bin/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/bin/spotify)       

(process:2): Gtk-WARNING **: Locale not supported by C library.                                                        
        Using the fallback 'C' locale.                     
Gtk-Message: Failed to load module "pk-gtk-module"         
/app/extra/share/spotify/spotify: /lib/libcurl.so.4: no version information available (required by /app/extra/share/spotify/spotify)                                                                                                          
/proc/self/exe: /lib/libcurl.so.4: no version information available (required by /proc/self/exe)                       
[0823/215410.848378:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process.                                                                                                                     
[0823/215410.851430:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain                                                                                                                     
[0823/215410.854232:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.                          
[0823/215410.854360:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.                          
[0823/215410.854425:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.                          
[0823/215410.854508:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.                          
[0823/215410.854564:ERROR:browser_gpu_channel_host_factory.cc(125)] Failed to create channel.                          

flatpak version 0.9.7
libostree version 2017.10

This rings a bell? For now I'm closing the bug. Thanks!
